name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
  - cron: "3 0 * * *"

jobs:
  update-card:
    name: Update LAPRAS Card
    runs-on: ubuntu-latest
    steps:
    - uses: kawamataryo/lapras-card-readme@v1.3.0
      with:
        SHARE_ID: "nnsnodnb"
        ICON_FIRST: "#03102f"
        ICON_SECOND: "#1688bf"
        BACKGROUND_FIRST: "#020e27"
        BACKGROUND_SECOND: "#0e5593"
        LANG: "en"
